# Generated by Django 5.0.2 on 2024-02-28 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 8, 23, 45, 347522, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='65cb2fc03cc06a22302742ab405f11b6ba1033d17bfc64af103f3a8dc327a9d4', max_length=64, null=True),
        ),
    ]
