# Generated by Django 5.0.2 on 2024-02-29 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_activation_expires_at_alter_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 9, 52, 52, 601771, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='40ea29cdd6c71626ed61b324d98685b57dcefbb7743011314f9fe762a399f484', max_length=64, null=True),
        ),
    ]
