# Generated by Django 5.0.2 on 2024-02-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_activation_expires_at_alter_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='activated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='bebff8de7bc8538897990d0741fc4b98b669e6700dcb083a4abfad2e60521cc5', max_length=64),
        ),
    ]
