# Generated by Django 5.0.2 on 2024-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_activation_activated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='fad1a4174b914bf5c4256e3b0ee88553054017e5d34100d29d2b3f4d5500847c', max_length=64),
        ),
    ]
