# Generated by Django 5.0.2 on 2024-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='297db4c12cf5b06678304445cc206be1eb58fcb19b104a57df1d27684518bcc8', max_length=64),
        ),
    ]
