# Generated by Django 5.0.2 on 2024-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='18ddc4eee54ebcad011e34d287add63045d13ece41275af99bc1cbdbad0f0a90', max_length=64),
        ),
    ]
