# Generated by Django 5.0.2 on 2024-03-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='e710bbed0efa3d359165ddb786268266e046c078e0427050d3010bc6b25e6d4f', max_length=64),
        ),
    ]
