# Generated by Django 5.0.2 on 2024-03-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='98745a884de35acbf4722bb15ef22d497fde3135cc4712fdc0b52941cd175cea', max_length=64),
        ),
    ]
