# Generated by Django 5.0.2 on 2024-03-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='67ac0b80763ded93143bdf4fde2921f56540a2bec4c076523068584625c43064', max_length=64),
        ),
    ]
