# Generated by Django 5.0.2 on 2024-02-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(blank=True, max_length=200, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('gen', models.CharField(blank=True, max_length=100, null=True)),
                ('rezumat', models.TextField(blank=True, null=True)),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
